version: '3.8'

services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform
    working_dir: /infra
    volumes:
      - .:/infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}